version: "3"

services:
    tor:
        image: "toronsynology/tor-client-minimal"
        volumes:
            - ./conf/torrc:/etc/tor/torrc:ro
        expose:
          - "9150"
    nginx:
        image: nginx:latest
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
              - tor
        ports:
              - "4000:4000"
